name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec

    - name: Run Rubocop
      run: bundle exec rubocop
      if: matrix.ruby == '3.3'

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      if: matrix.ruby == '3.3'
      with:
        files: ./coverage/.resultset.json
        flags: unittests
        name: codecov-umbrella

